language: perl
cache: bundler

bundler_args: "--deployment"
sudo: required

matrix:
  include:
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'

before_install:
- sudo apt-get install -qq libgd2-xpm-dev

notifications:
  email: false
  slack:
    secure: MG/Ux8oDkG19FMKdW1dUh0RKY4auisraGeASgbKpngI2q22RvdbeWIq1CB8Qh/cBZIYvlD9CcM0FlbBekTM9iE3rH8Cm9J/kIQaYA2Cenz512nkaGZ78AtTwaCqfaOXmm4GfoG/BXBEP3CSZar1z3zHraxkn2QLHbLt+fEfH4qV4vgOaFiKiPGb5MYuBy4dLSmW7Z34synFqZgn13tYPUi6GyQcAksJJCHvlyfW4ziP6fCo0qHOacoNOyOgAy9y75auUUh13RGk630h4daND+DHF18qsUznu3BVz+OZfICYwQSpl/sdECTxLQRMAWvPqr3a1PdiN2xkyJ62UwA87Za8LGbTH8QkFvHjy2plmUSHGtv9cGkxoe++lxVG9RnWWMqAZghGs1A7kJptKfX6A8amq1q7PYz8VcMShkmGCxVAxMEwo94fJibPsQp3dv0v6ahdOKp80SWgIM+LykM4h1EjQ4wb7NigPYHeW2KRoskIPj5djiBfNaybyd/RvMaME5FjVAydDRaQ0h6ee5ESdA5ugEijvKug8bSiIFMLf2aSnbhnms3vrpzYNyHeWOWlc+iz2lITrjiAgRdVwF4QCmpAh9BP0Oe4tC9H1fU6gtZcbsGiABt06VPYUngUlqNON5x4GJmX7YXpRyjz0qRsPluK1IEOTEC9tBp/uzjY70gw=
